import type { Asset } from "@/types/asset"

export const mockAssets: Asset[] = [
  // Stocks
  {
    id: "1",
    name: "Innovatech Solutions",
    symbol: "INVT",
    assetClass: "Stock",
    type: "Public",
    currentPrice: 150.75,
    priceMovement: "Up",
    shortTermGainPotential: "High",
    mediumTermGainPotential: "Medium",
    sentiment: "Positive",
    keyIndicatorsSummary: "Strong RSI, Above MA50, Positive Earnings",
    newsHighlight: "Innovatech announces breakthrough in AI research, stock surges.",
    recommendation: "Strong Buy",
    logoUrl: "/placeholder.svg?height=32&width=32",
    volume: 1250000,
    buyVolume24h: 800000,
    sellVolume24h: 300000,
  },
  {
    id: "2",
    name: "GreenFuture Energy",
    assetClass: "Stock",
    type: "Private",
    valuationEst: "$500M - $700M",
    priceMovement: "Stable",
    shortTermGainPotential: "Medium",
    mediumTermGainPotential: "High",
    sentiment: "Positive",
    keyIndicatorsSummary: "Series C funding, Strong market demand for renewables",
    newsHighlight: "GreenFuture secures major government contract for solar panel installations.",
    recommendation: "Speculative",
    logoUrl: "/placeholder.svg?height=32&width=32",
  },
  // Cryptocurrencies
  {
    id: "crypto-1",
    name: "Bitcoin",
    symbol: "BTC",
    assetClass: "Crypto",
    blockchain: "Bitcoin",
    currentPrice: 68500.0,
    priceMovement: "Up",
    marketCap: 1350000000000, // 1.35 Trillion
    circulatingSupply: 19700000,
    maxSupply: 21000000,
    shortTermGainPotential: "Medium",
    mediumTermGainPotential: "High",
    sentiment: "Positive",
    keyIndicatorsSummary: "Approaching resistance, High network activity",
    newsHighlight: "Bitcoin ETF inflows continue to show strong institutional interest.",
    recommendation: "Buy",
    logoUrl: "/placeholder.svg?height=32&width=32",
    volume: 35000000000, // 35 Billion
    buyVolume24h: 20000000000,
    sellVolume24h: 15000000000,
  },
  {
    id: "crypto-2",
    name: "Ethereum",
    symbol: "ETH",
    assetClass: "Crypto",
    blockchain: "Ethereum",
    currentPrice: 3800.0,
    priceMovement: "Stable",
    marketCap: 450000000000, // 450 Billion
    circulatingSupply: 120000000,
    maxSupply: null, // No max supply
    shortTermGainPotential: "High",
    mediumTermGainPotential: "High",
    sentiment: "Positive",
    keyIndicatorsSummary: "Upcoming network upgrade, Strong DeFi ecosystem",
    newsHighlight: "Ethereum's Dencun upgrade successfully reduces transaction fees on L2s.",
    recommendation: "Strong Buy",
    logoUrl: "/placeholder.svg?height=32&width=32",
    volume: 18000000000, // 18 Billion
    buyVolume24h: 10000000000,
    sellVolume24h: 8000000000,
  },
  {
    id: "crypto-3",
    name: "DogeCoin",
    symbol: "DOGE",
    assetClass: "Crypto",
    blockchain: "Dogecoin",
    currentPrice: 0.15,
    priceMovement: "Down",
    marketCap: 20000000000, // 20 Billion
    circulatingSupply: 140000000000,
    maxSupply: null,
    shortTermGainPotential: "Low",
    mediumTermGainPotential: "Low",
    sentiment: "Neutral",
    keyIndicatorsSummary: "High volatility, Community driven",
    newsHighlight: "DogeCoin price fluctuates based on social media trends.",
    recommendation: "Speculative",
    logoUrl: "/placeholder.svg?height=32&width=32",
    volume: 1500000000, // 1.5 Billion
    buyVolume24h: 700000000,
    sellVolume24h: 800000000,
  },
  // More stocks
  {
    id: "3",
    name: "Legacy Corp",
    symbol: "LGCY",
    assetClass: "Stock",
    type: "Public",
    currentPrice: 45.2,
    priceMovement: "Down",
    shortTermGainPotential: "Low",
    mediumTermGainPotential: "Low",
    sentiment: "Negative",
    keyIndicatorsSummary: "Below MA200, Declining revenue, Analyst downgrades",
    newsHighlight: "Legacy Corp faces increased competition, posts lower than expected quarterly results.",
    recommendation: "Sell",
    logoUrl: "/placeholder.svg?height=32&width=32",
    volume: 850000,
    buyVolume24h: 200000,
    sellVolume24h: 600000,
  },
]
