import type { Stock } from "@/types/stock" // We'll define this type

export const mockStocks: Stock[] = [
  {
    id: "1",
    name: "Innovatech Solutions",
    ticker: "INVT",
    type: "Public",
    currentPrice: 150.75,
    priceMovement: "Up",
    shortTermGainPotential: "High",
    mediumTermGainPotential: "Medium",
    sentiment: "Positive",
    keyIndicatorsSummary: "Strong RSI, Above MA50, Positive Earnings",
    newsHighlight: "Innovatech announces breakthrough in AI research, stock surges.",
    recommendation: "Strong Buy",
    logoUrl: "/placeholder.svg?height=32&width=32",
    volume: 1250000,
    buyVolume24h: 800000,
    sellVolume24h: 300000,
  },
  {
    id: "2",
    name: "GreenFuture Energy",
    type: "Private",
    valuationEst: "$500M - $700M",
    priceMovement: "Stable",
    shortTermGainPotential: "Medium",
    mediumTermGainPotential: "High",
    sentiment: "Positive",
    keyIndicatorsSummary: "Series C funding, Strong market demand for renewables",
    newsHighlight: "GreenFuture secures major government contract for solar panel installations.",
    recommendation: "Speculative",
    logoUrl: "/placeholder.svg?height=32&width=32",
    // Volume and buy/sell ratio might be N/A or not applicable for private companies in this context
    volume: undefined,
    buyVolume24h: undefined,
    sellVolume24h: undefined,
  },
  {
    id: "3",
    name: "Legacy Corp",
    ticker: "LGCY",
    type: "Public",
    currentPrice: 45.2,
    priceMovement: "Down",
    shortTermGainPotential: "Low",
    mediumTermGainPotential: "Low",
    sentiment: "Negative",
    keyIndicatorsSummary: "Below MA200, Declining revenue, Analyst downgrades",
    newsHighlight: "Legacy Corp faces increased competition, posts lower than expected quarterly results.",
    recommendation: "Sell",
    logoUrl: "/placeholder.svg?height=32&width=32",
    volume: 850000,
    buyVolume24h: 200000,
    sellVolume24h: 600000,
  },
  {
    id: "4",
    name: "BioHealth Pharma",
    ticker: "BHPH",
    type: "Public",
    currentPrice: 88.0,
    priceMovement: "Stable",
    shortTermGainPotential: "Medium",
    mediumTermGainPotential: "Medium",
    sentiment: "Neutral",
    keyIndicatorsSummary: "Phase 3 trials ongoing, Mixed analyst sentiment",
    newsHighlight: "BioHealth Pharma presents promising early data for new drug candidate.",
    recommendation: "Hold",
    logoUrl: "/placeholder.svg?height=32&width=32",
    volume: 550000,
    buyVolume24h: 250000,
    sellVolume24h: 200000,
  },
  {
    id: "5",
    name: "QuantumLeap AI",
    type: "Private",
    valuationEst: "$1.2B - $1.5B (Pre-IPO)",
    priceMovement: "Up",
    shortTermGainPotential: "N/A",
    mediumTermGainPotential: "High",
    sentiment: "Positive",
    keyIndicatorsSummary: "Disruptive tech, Strong IP portfolio, Experienced team",
    newsHighlight: "QuantumLeap AI rumored to be exploring IPO options within next 18 months.",
    recommendation: "Speculative",
    logoUrl: "/placeholder.svg?height=32&width=32",
    volume: undefined,
    buyVolume24h: undefined,
    sellVolume24h: undefined,
  },
  {
    id: "6",
    name: "NextGen Retail",
    ticker: "NXRT",
    type: "Public",
    currentPrice: 210.5,
    priceMovement: "Up",
    shortTermGainPotential: "Medium",
    mediumTermGainPotential: "High",
    sentiment: "Positive",
    keyIndicatorsSummary: "Strong e-commerce growth, Expanding market share",
    newsHighlight: "NextGen Retail reports record online sales for Q2.",
    recommendation: "Buy",
    logoUrl: "/placeholder.svg?height=32&width=32",
    volume: 1500000,
    buyVolume24h: 900000,
    sellVolume24h: 400000,
  },
]
